schemas:
  bootstrap: 8000
  sitedrupalfilmes: 8000
favicon:
  mimetype: image/gif
  path: 'public://icons8-monitor.gif'
  url: 'http://localhost/drupalhandsontest/web/themes/sitedrupalfilmes/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 0
table_responsive: '-1'
cdn_theme: slate
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
langcode: pt-br
